language: scala
sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

scala:
  - 2.10.4

install:
  - wget "http://mirrors.ocf.berkeley.edu/apache/spark/spark-1.6.1/spark-1.6.1-bin-cdh4.tgz"
  - mkdir spark && tar xvf "spark-1.6.1-bin-cdh4.tgz" -C spark

env:
  - SPARK_HOME="$HOME/spark/"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/spark

script: ./gradlew clean build -x check -x :sparkling-water-py:build -PsparklingTestEnv=local -PsparkHome=$SPARK_HOME

