language: scala
sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

scala:
  - 2.10.4

install:
  - wget "http://d3kbcqa49mib13.cloudfront.net/spark-1.4.1-bin-cdh4.tgz"
  - mkdir spark && tar xvf "spark-1.4.1-bin-cdh4.tgz" -C spark

env:
  - SPARK_HOME="$HOME/spark/"

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/spark

script: ./gradlew clean build -x check -x :sparkling-water-py:build -PsparklingTestEnv=local -PsparkHome=$SPARK_HOME

